# Generated by Django 4.2.21 on 2025-05-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_recon', '0002_bankstatement_deposit_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
