# Generated by Django 4.2.21 on 2025-05-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_recon', '0003_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
